### ISSUE TITLE
Add support for Vite

### ISSUE THREAD

**Issue by TheLostLambda** [pyodide/pyodide-webpack-plugin#16]
I've found it very very tricky to get Pyodide working with Vite as a bundler (which I feel has become pretty popular now) and had to give up to load things from a CDN instead.

It looks like this is what I was missing (but I couldn't find mention of it anywhere except for some random Github comment — finding any example of bundling Pyodide took me hours), but it looks like it will only work for people using Webpack.

Is it possible to develop something similar for Vite? Or is there an even simpler, plugin-free solution that I'm missing?

Sorry for the trouble and thanks in advance!

**Comment by mneil** [comment]
I've used Vite exactly once so I do not have input into how this would be integrated. I'm very positive that it is possible. This repository is specifically about a plugin for webpack. You have already commented on two other separate issues about this on the Pyodide main repo. That is a much better place to have this discussion. 

I suggest opening a new, specific issue for Vite in the Pyodide repo rather than trying to comment on existing open issues that do not mention Vite as a bundler in the title or description. A bundler for Vite is different than a plugin for Webpack, or for Rollup, or for Parcel. 

I am closing this issue since it's not relevant to this project.
